
[workspace]
members = ["weblab-macros", "example-project", "weblab-assignment-structure", "cargo-weblabtest", "weblab", "weblab-docker/user_code", "tests"]
default-members = ["weblab-macros", "example-project", "weblab-assignment-structure", "cargo-weblabtest", "weblab", "tests"]

